name: Build CI
run-name: Build CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  focal:
    runs-on: [self-hosted, linux, x64, focal]
    timeout-minutes: 45
    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ secrets.NPM_REGISTRY_URL }}"
          echo "::add-mask::${{ secrets.NPM_REGISTRY_AUTH }}"
          echo "::add-mask::${{ secrets.CODECOV_TOKEN }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_1 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_2 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_1 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_2 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_4 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_5 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_6 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_7 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_8 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_1 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_2 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_3 }}"
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set ulimit
        run: ulimit -n 9999
      - name: Pre-Installation
        shell: 'script -q -e -c "bash {0}"'
        run: ./src/install/pre_install.sh
      - name: Install FACT
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./src/install.py -U -R -N -L DEBUG
      - name: Unit Tests
        shell: 'script -q -e -c "bash {0}"'
        run: |
          python3 -m pip install codecov
          pytest --cov=.
jobs:
  focal:
    runs-on: [self-hosted, linux, x64, focal]
    timeout-minutes: 45
    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ secrets.NPM_REGISTRY_URL }}"
          echo "::add-mask::${{ secrets.NPM_REGISTRY_AUTH }}"
          echo "::add-mask::${{ secrets.CODECOV_TOKEN }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_1 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_2 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_1 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_2 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_4 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_5 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_6 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_7 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_8 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_1 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_2 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_3 }}"
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set ulimit
        run: ulimit -n 9999
      - name: Pre-Installation
        shell: 'script -q -e -c "bash {0}"'
        run: ./src/install/pre_install.sh
      - name: Install FACT
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./src/install.py -U -R -N -L DEBUG
      - name: Unit Tests
        shell: 'script -q -e -c "bash {0}"'
        run: |
          python3 -m pip install codecov
          pytest --cov=.
  jammy:
    runs-on: [self-hosted, linux, x64, jammy]
    timeout-minutes: 45
    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ secrets.NPM_REGISTRY_URL }}"
          echo "::add-mask::${{ secrets.NPM_REGISTRY_AUTH }}"
          echo "::add-mask::${{ secrets.CODECOV_TOKEN }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_1 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_2 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_1 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_2 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_4 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_5 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_6 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_7 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_8 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_1 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_2 }}"
          echo "::add-mask::${{ secrets.SECRET_STRINGS_3 }}"
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set ulimit
        run: ulimit -n 9999
      - name: Pre-Installation
        shell: 'script -q -e -c "bash {0}"'
        run: ./src/install/pre_install.sh
      - name: Install FACT
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./src/install.py -U -R -N -L DEBUG
      - name: Unit Tests
        shell: 'script -q -e -c "bash {0}"'
        run: |
          python3 -m pip install codecov
          pytest --cov=.
